management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

server:
  contextPath: /
  port: 8080

info:
  application:
    name: TechPanther Search Engine - BackEnd
    description: API RESTFul para los servicios de la app TechPanther Search Engine
    author: Omar Arvelo
    version: '1'

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev